export function getRecipes() {
  return [
    {
      id: 0,
      title: "Kokos\u00ADolja och passions\u00ADfrukts\u00ADkladd\u00ADkaka",
      description:
        "Denna tropiska kladdkaka kombinerar krämig kokosnötsolja med syrlig passionsfrukt för en exotisk smakupplevelse som tar dig direkt till paradiset.",
      ingredients: [
        "100 g kokosnötsolja",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "2 passionsfrukter",
      ],
      steps: [
        "1. Sätt ugnen på 175°C",
        "2. Smält kokosnötsoljan",
        "3. Skrapa ur passionsfrukterna",
        "4. Vispa ägg och socker",
        "5. Rör i olja och passionsfrukt",
        "6. Blanda i mjöl och kakao",
        "7. Grädda i 22 minuter",
      ],
      rating: 2.6,
      categories: ["Tropiska kladdkakor", "Veganska kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 1,
      title: "Wasabi och sesam\u00ADkladd\u00ADkaka",
      description:
        "Denna asiatiskt inspirerade kladdkaka erbjuder en perfekt balans mellan het wasabi och nötig sesam för en oförglömlig kulinarisk upplevelse.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "1-2 tsk wasabipasta",
        "0.5 dl rostade sesamfrön",
        "1 msk sesamolja",
      ],
      steps: [
        "1. Sätt ugnen på 175°C",
        "2. Smält smör med sesamolja",
        "3. Vispa ägg och socker",
        "4. Rör i smörblandning och wasabi",
        "5. Blanda i mjöl, kakao och sesamfrön",
        "6. Grädda i 18 minuter",
      ],
      rating: 4.0,
      categories: ["Asiatiska kladdkakor", "Kryddstarka kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 2,
      title: "Rökig bacon och lönn\u00ADsiraps\u00ADkladd\u00ADkaka",
      description:
        "En amerikansk klassiker där krispigt rökt bacon möter söt lönnsirap i denna unika kombination av sött och salt som kommer att överraska dina smaklökar.",
      ingredients: [
        "100 g smör",
        "100 g rökt bacon",
        "2 ägg",
        "1 dl strösocker",
        "1 dl lönnsirap",
        "1.5 dl vetemjöl",
        "4 msk kakao",
      ],
      steps: [
        "1. Sätt ugnen på 175°C",
        "2. Stek bacon tills det är krispigt",
        "3. Smält smör med baconsmaken",
        "4. Vispa ägg, socker och sirap",
        "5. Blanda alla ingredienser",
        "6. Grädda i 20 minuter",
      ],
      rating: 1.2,
      categories: ["Söta och salta kladdkakor", "Amerikanska kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 3,
      title: "Saffran och pinje\u00ADnöts\u00ADkladd\u00ADkaka",
      description:
        "Denna lyxiga italienska kladdkaka kombinerar exklusiv saffran med krämiga pinjenötter och frisk apelsin för en sofistikerad efterrätten.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "0.5 g saffran",
        "1 dl pinjenötter",
        "rivet skal av 1 apelsin",
      ],
      steps: [
        "1. Sätt ugnen på 170°C",
        "2. Mortla saffran med 1 msk varmt vatten",
        "3. Smält smöret",
        "4. Vispa ägg och socker med saffran",
        "5. Rör i smör, apelsinskal och nötter",
        "6. Blanda i mjöl och kakao",
        "7. Grädda i 22 minuter",
      ],
      rating: 5,
      categories: ["Lyxiga kladdkakor", "Italienska kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 4,
      title: "Tequila och lime\u00ADkladd\u00ADkaka",
      description:
        "En festlig mexikansk kladdkaka där stark tequila och syrlig lime skapar en fräsch och spännande smakkombination som perfekt passar till kalas.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "4 msk tequila",
        "rivet skal och saft av 2 lime",
      ],
      steps: [
        "1. Sätt ugnen på 170°C",
        "2. Smält smöret",
        "3. Vispa ägg och socker",
        "4. Rör i smör, tequila och lime",
        "5. Blanda i mjöl och kakao",
        "6. Grädda i 20 minuter",
      ],
      rating: 3.8,
      categories: ["Alkoholhaltiga kladdkakor", "Mexikanska kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 5,
      title: "Mjölk\u00ADfri havre\u00ADdrycks\u00ADkladd\u00ADkaka",
      description:
        "Denna skonsamma veganska variant använder havredryck för att skapa en mjuk och fuktig kladdkaka som är perfekt för den mjölkfria dieten.",
      ingredients: [
        "100 g veganskt smör",
        "1.5 dl havredryck",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "4 msk kakao",
        "1 tsk bakpulver",
      ],
      steps: [
        "1. Sätt ugnen på 175°C",
        "2. Smält veganskt smör",
        "3. Vispa ägg och socker",
        "4. Rör i smör och havredryck",
        "5. Blanda i mjöl, kakao och bakpulver",
        "6. Grädda i 22 minuter",
      ],
      rating: 3.2,
      categories: ["Mjölkfria kladdkakor", "Veganska kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 6,
      title: "Zucchini och choklad\u00ADkladd\u00ADkaka",
      description:
        "En överraskande nyttig kladdkaka där finkornig zucchini ger fantastisk fuktighet till den rika chokladsmaken utan att synas.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl rivet zucchini",
        "1.5 dl vetemjöl",
        "4 msk kakao",
        "1 tsk kanel",
      ],
      steps: [
        "1. Sätt ugnen på 175°C",
        "2. Riv zucchinin och låt rinna av",
        "3. Smält smöret",
        "4. Vispa ägg och socker",
        "5. Rör i smör och zucchini",
        "6. Blanda i mjöl, kakao och kanel",
        "7. Grädda i 25 minuter",
      ],
      rating: 4.8,
      categories: ["Grönsakskladdkakor", "Nyttiga kladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 7,
      title: "Pop\u00ADcorn och karamell\u00ADkladd\u00ADkaka",
      description:
        "Denna unika kladdkaka kombinerar krispiga popcorn med söt karamell för en rolig texturmässig överraskning i varje tugga.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "2 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "2 dl popcorn",
        "0.5 dl karamellsås",
      ],
      steps: [
        "1. Sätt ugnen på 170°C",
        "2. Gör popcorn och krossa lätt",
        "3. Smält smöret",
        "4. Vispa ägg och socker",
        "5. Rör i smör och karamell",
        "6. Blanda i mjöl, kakao och popcorn",
        "7. Grädda i 23 minuter",
      ],
      rating: 3.7,
      categories: ["Krispiga kladdkakor", "Karamellkladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 8,
      title: "Rökig paprika och manchego\u00ADkladd\u00ADkaka",
      description:
        "En spansk inspirerad kladdkaka med nötig manchegoost och rökig paprika som skapar en komplex och minnesvärd smakupplevelse.",
      ingredients: [
        "100 g smör",
        "100 g manchegoost",
        "2 ägg",
        "1.5 dl strösocker",
        "1.5 dl vetemjöl",
        "3 msk kakao",
        "1 tsk rökpaprika",
      ],
      steps: [
        "1. Sätt ugnen på 165°C",
        "2. Riv osten grovt",
        "3. Smält smöret",
        "4. Vispa ägg och socker",
        "5. Rör i smör, ost och paprika",
        "6. Blanda i mjöl och kakao",
        "7. Grädda i 28 minuter",
      ],
      rating: 0.6,
      categories: ["Spanska kladdkakor", "Ostkladdkakor"],
      cookTimeMinutes: 15,
    },
    {
      id: 9,
      title: "Svart vinbär och port\u00ADvins\u00ADkladd\u00ADkaka",
      description:
        "En sofistikerad vuxenkladdkaka där syrliga svarta vinbär och mustigt portvin skapar en djup och fruktig smakprofil.",
      ingredients: [
        "100 g smör",
        "2 ägg",
        "1.5 dl strösocker",
        "1.5 dl vetemjöl",
        "4 msk kakao",
        "1 dl svarta vinbär",
        "4 msk portvin",
      ],
      steps: [
        "1. Sätt ugnen på 170°C",
        "2. Smält smöret",
        "3. Vispa ägg och socker",
        "4. Rör i smör och portvin",
        "5. Blanda i mjöl, kakao och vinbär",
        "6. Grädda i 24 minuter",
      ],
      rating: 3.2,
      categories: ["Vuxna kladdkakor", "Bärkladdkakor"],
      cookTimeMinutes: 15,
    },
  ];
}
